# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0a4e1b4d497a23b9b55f96c205430f457329e2f74b13675a7bebb38c88792029ac6e60b05ae1c883b7a5603f5b6d77a01560896909652f79a3d1a71f44d305b

test:
  secret_key_base: 66e52c4ca519e2f28205b15b71c1daa64e633ba6341bdc76445321c74920dcee4104bf552e39bbf9ee0aea95e6627f05e514286102728d016c23eb315d37a2ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
